"""Generates fake operational orders dataset → data/pedidos.csv + db/init.sql"""

import numpy as np
import pandas as pd
from pathlib import Path

np.random.seed(7)

CLIENTES = [f"Cliente {chr(65+i)}" for i in range(20)]
PRODUTOS = {
    "Notebook Pro":     dict(preco=3200, categoria="Eletrônicos"),
    "Monitor 27\"":     dict(preco=1100, categoria="Eletrônicos"),
    "Cadeira Ergonômica": dict(preco=890, categoria="Mobiliário"),
    "Mesa Standing":    dict(preco=1450, categoria="Mobiliário"),
    "Headset Gamer":    dict(preco=320,  categoria="Periféricos"),
    "Teclado Mecânico": dict(preco=280,  categoria="Periféricos"),
    "Webcam HD":        dict(preco=190,  categoria="Periféricos"),
    "SSD 1TB":          dict(preco=420,  categoria="Eletrônicos"),
}
VENDEDORES = ["Ana Silva", "Bruno Costa", "Carlos Lima",
              "Diana Santos", "Eduardo Rocha"]
REGIOES = ["Sudeste", "Sul", "Nordeste", "Centro-Oeste", "Norte"]
STATUS = ["Entregue", "Entregue", "Entregue", "Em trânsito", "Cancelado"]  # weighted

N = 1_200
START, END = "2024-01-01", "2024-12-31"


def generate():
    datas_pedido = pd.to_datetime(
        np.random.choice(pd.date_range(START, END), size=N)
    )

    produtos = np.random.choice(list(PRODUTOS.keys()), size=N)
    qtd = np.random.randint(1, 6, size=N)
    precos = np.array([PRODUTOS[p]["preco"] for p in produtos], dtype=float)
    precos *= np.random.uniform(0.9, 1.1, size=N)  # variação de preço
    valor_total = (precos * qtd).round(2)

    status_arr = np.random.choice(STATUS, size=N)

    prazo_dias = np.random.randint(3, 15, size=N)
    entrega_real = np.where(
        status_arr == "Entregue",
        prazo_dias + np.random.randint(-2, 6, size=N),
        None,
    )

    df = pd.DataFrame({
        "id":             range(1, N + 1),
        "data_pedido":    datas_pedido.date,
        "cliente":        np.random.choice(CLIENTES, size=N),
        "produto":        produtos,
        "categoria":      [PRODUTOS[p]["categoria"] for p in produtos],
        "vendedor":       np.random.choice(VENDEDORES, size=N),
        "regiao":         np.random.choice(REGIOES, size=N),
        "qtd":            qtd,
        "valor_unitario": precos.round(2),
        "valor_total":    valor_total,
        "status":         status_arr,
        "prazo_dias":     prazo_dias,
        "entrega_dias":   entrega_real,
    })
    df = df.sort_values("data_pedido").reset_index(drop=True)

    out_csv = Path(__file__).parent / "data" / "pedidos.csv"
    df.to_csv(out_csv, index=False)
    print(f"✓ {len(df)} pedidos → {out_csv}")

    _write_sql(df)


def _write_sql(df: pd.DataFrame):
    out = Path(__file__).parent / "db" / "init.sql"
    lines = [
        "-- Auto-generated by generate_data.py\n",
        "DROP TABLE IF EXISTS pedidos;\n",
        "CREATE TABLE pedidos (\n",
        "  id            SERIAL PRIMARY KEY,\n",
        "  data_pedido   DATE,\n",
        "  cliente       VARCHAR(50),\n",
        "  produto       VARCHAR(50),\n",
        "  categoria     VARCHAR(30),\n",
        "  vendedor      VARCHAR(50),\n",
        "  regiao        VARCHAR(30),\n",
        "  qtd           INT,\n",
        "  valor_unitario NUMERIC(10,2),\n",
        "  valor_total   NUMERIC(10,2),\n",
        "  status        VARCHAR(20),\n",
        "  prazo_dias    INT,\n",
        "  entrega_dias  INT\n",
        ");\n\n",
    ]

    lines.append("INSERT INTO pedidos (data_pedido,cliente,produto,categoria,vendedor,regiao,qtd,valor_unitario,valor_total,status,prazo_dias,entrega_dias) VALUES\n")
    rows = []
    for _, r in df.iterrows():
        entrega = "NULL" if pd.isna(r["entrega_dias"]) else int(r["entrega_dias"])
        rows.append(
            f"  ('{r.data_pedido}','{r.cliente}','{r.produto}','{r.categoria}',"
            f"'{r.vendedor}','{r.regiao}',{r.qtd},{r.valor_unitario},{r.valor_total},"
            f"'{r.status}',{r.prazo_dias},{entrega})"
        )
    lines.append(",\n".join(rows) + ";\n")

    out.write_text("".join(lines))
    print(f"✓ SQL gerado → {out}")


if __name__ == "__main__":
    generate()
